// <auto-generated />
using System;
using LevelsOnIceSalon.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LevelsOnIceSalon.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.AppointmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("InspirationReference")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFirstTimeClient")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<string>("Occasion")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly?>("PreferredDate")
                        .HasColumnType("date");

                    b.Property<string>("PreferredStylistName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<TimeOnly?>("PreferredTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamMemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("AppointmentRequests", (string)null);
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReplyNotes")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages", (string)null);
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Faqs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Yes. Walk-ins are welcome, but bookings are recommended for busy periods and longer appointments.",
                            Category = "Booking",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsDeleted = false,
                            IsPublished = true,
                            Question = "Do you accept walk-ins?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "You submit a booking request online, and the salon follows up to confirm the final time and service details.",
                            Category = "Booking",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsDeleted = false,
                            IsPublished = true,
                            Question = "How does the appointment request work?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Yes. Levels On Ice Salon offers premium styling suitable for bridal, events, and special occasion beauty needs.",
                            Category = "Services",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsDeleted = false,
                            IsPublished = true,
                            Question = "Do you offer bridal or special occasion services?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Clients can enjoy free WiFi, complimentary refreshments, and a stylish atmosphere designed for comfort and confidence.",
                            Category = "Visit",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsDeleted = false,
                            IsPublished = true,
                            Question = "What makes the salon experience comfortable?"
                        });
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.GalleryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("ImageType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("GalleryImages", (string)null);
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.OpeningHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek")
                        .IsUnique();

                    b.ToTable("OpeningHours", (string)null);
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.PromotionBanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CallToActionText")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CallToActionUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("StartsOn")
                        .HasColumnType("date");

                    b.Property<int>("Style")
                        .HasColumnType("integer");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PromotionBanners", (string)null);
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("FullDescription")
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBookableOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("PricingType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            DurationMinutes = 80,
                            FullDescription = "A premium gel manicure with precision prep, shaping, cuticle care, and a glossy salon finish that feels polished, soft, and photo-ready.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Gloss Theory Gel Set",
                            Price = 320m,
                            PricingType = 2,
                            ServiceCategoryId = 1,
                            ShortDescription = "A sleek gel finish for girls who love clean, expensive-looking nails every day.",
                            Slug = "gloss-theory-gel-set"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            DurationMinutes = 140,
                            FullDescription = "Our statement acrylic set is built for noticeable beauty with sculpted shape, length customization, and a crisp, luxe finish that photographs beautifully.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Iced-Out Acrylic Signature Set",
                            Price = 520m,
                            PricingType = 2,
                            ServiceCategoryId = 1,
                            ShortDescription = "A bold acrylic look with shape, length, and attitude for girls who love a standout finish.",
                            Slug = "iced-out-acrylic-signature-set"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            DurationMinutes = 90,
                            FullDescription = "Perfect for maintaining a polished acrylic or gel look, this refill includes reshaping, balancing, and a refined finish that keeps your set looking elevated.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "French Girl Refill",
                            Price = 380m,
                            PricingType = 2,
                            ServiceCategoryId = 1,
                            ShortDescription = "A fresh refill for clients who love soft luxury nails with a clean designer finish.",
                            Slug = "french-girl-refill"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            DurationMinutes = 120,
                            FullDescription = "This silk press service is designed for sleek movement, healthy shine, and a refined finish that feels expensive without looking overdone.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Silk Press & Sway Finish",
                            Price = 650m,
                            PricingType = 2,
                            ServiceCategoryId = 2,
                            ShortDescription = "A smooth, bouncy finish with movement, shine, and soft luxury energy.",
                            Slug = "silk-press-sway-finish"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            DurationMinutes = 90,
                            FullDescription = "A styled finish built around volume, shape, and softness for clients who want occasion-ready hair that still feels modern and wearable.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Soft Glam Curls Styling",
                            Price = 480m,
                            PricingType = 2,
                            ServiceCategoryId = 2,
                            ShortDescription = "Defined curls and a glossy finish for birthdays, dinners, graduations, and pretty-girl weekends.",
                            Slug = "soft-glam-curls-styling"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            DurationMinutes = 300,
                            FullDescription = "A client-favorite protective style with a clean parting pattern, natural fall, and a polished result that feels stylish from day one.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Knotless Braids, Mid-Back",
                            Price = 950m,
                            PricingType = 2,
                            ServiceCategoryId = 3,
                            ShortDescription = "Neat, lightweight knotless braids with a soft feminine finish and everyday luxury feel.",
                            Slug = "knotless-braids-mid-back"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            DurationMinutes = 360,
                            FullDescription = "This premium boho knotless style blends neat structure with soft loose detail, making it ideal for clients who want protective styling with movement and personality.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Boho Knotless Luxe",
                            Price = 1350m,
                            PricingType = 2,
                            ServiceCategoryId = 3,
                            ShortDescription = "A soft, romantic protective style with loose textured pieces for an elevated look.",
                            Slug = "boho-knotless-luxe"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            DurationMinutes = 120,
                            FullDescription = "A neat protective style with detail-focused parting and a sleek finish that works beautifully for everyday wear, holidays, and active weeks.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "Sleek Cornrow Design",
                            Price = 450m,
                            PricingType = 2,
                            ServiceCategoryId = 3,
                            ShortDescription = "A clean braided look with precise lines for sporty-chic, low-maintenance beauty.",
                            Slug = "sleek-cornrow-design"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            DurationMinutes = 35,
                            FullDescription = "A quick beauty add-on that shapes, tidies, and softly defines the brows for a more put-together finish.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "Brow Clean-Up & Tint",
                            Price = 180m,
                            PricingType = 1,
                            ServiceCategoryId = 4,
                            ShortDescription = "A polished brow refresh that sharpens your whole face in under an hour.",
                            Slug = "brow-clean-up-tint"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            DurationMinutes = 60,
                            FullDescription = "A lightweight glam makeup add-on designed to enhance features and complete your salon look without needing a full separate appointment.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Soft Glam Face Beat Add-On",
                            Price = 420m,
                            PricingType = 2,
                            ServiceCategoryId = 4,
                            ShortDescription = "A camera-friendly glam touch-up for clients pairing hair and beauty in one visit.",
                            Slug = "soft-glam-face-beat-add-on"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            DurationMinutes = 20,
                            FullDescription = "An easy beauty add-on that adds eye definition and softness, ideal before events, dates, birthdays, and content days.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "Lash Flick Finish",
                            Price = 150m,
                            PricingType = 1,
                            ServiceCategoryId = 4,
                            ShortDescription = "A flirty finishing touch for girls who want their salon look to feel complete.",
                            Slug = "lash-flick-finish"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            DurationMinutes = 150,
                            FullDescription = "A bridal planning appointment focused on trying the look, refining the finish, and building confidence around your final beauty direction.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Bridal Preview Styling Session",
                            Price = 950m,
                            PricingType = 2,
                            ServiceCategoryId = 5,
                            ShortDescription = "A consultation-led preview for brides who want to feel fully sure before the big day.",
                            Slug = "bridal-preview-styling-session"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            DurationMinutes = 180,
                            FullDescription = "A bespoke bridal hair service tailored to the dress, mood board, veil, and wedding energy, with a refined finish that still feels modern and youthful.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Wedding Morning Glam Hair",
                            PricingType = 3,
                            ServiceCategoryId = 5,
                            ShortDescription = "Elegant bridal hairstyling with a soft luxury finish made for photos and unforgettable entrances.",
                            Slug = "wedding-morning-glam-hair"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            DurationMinutes = 180,
                            FullDescription = "Created for matric dance and milestone celebrations, this signature glam service is youthful, elegant, and styled to feel memorable on camera and in person.",
                            IsActive = true,
                            IsBookableOnline = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Matric Dance Signature Glam",
                            Price = 1200m,
                            PricingType = 2,
                            ServiceCategoryId = 5,
                            ShortDescription = "A polished hair-and-beauty look for entrance moments, photos, and all-night confidence.",
                            Slug = "matric-dance-signature-glam"
                        });
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ServiceCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-gloss nail artistry for soft luxury girls, statement sets, and polished everyday confidence.",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nails",
                            Slug = "nails"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Effortless glam, soft luxury styling, and event-ready looks with a premium salon finish.",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hairstyles",
                            Slug = "hairstyles"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Protective styling that feels neat, feminine, trend-aware, and beautifully camera-ready.",
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Braids & Protective Styles",
                            Slug = "braids-protective-styles"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Finishing touches that elevate your appointment from simple upkeep to a full beauty moment.",
                            DisplayOrder = 4,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Beauty Add-ons",
                            Slug = "beauty-add-ons"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant beauty styling for weddings, celebrations, shoots, graduations, and unforgettable entrances.",
                            DisplayOrder = 5,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bridal / Special Occasion",
                            Slug = "bridal-special-occasion"
                        });
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SiteSettings", (string)null);
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FullBio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("InstagramHandle")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("ShortBio")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Testimonials", (string)null);
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.AppointmentRequest", b =>
                {
                    b.HasOne("LevelsOnIceSalon.Domain.Entities.Service", "Service")
                        .WithMany("AppointmentRequests")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LevelsOnIceSalon.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("AppointmentRequests")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Service");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.GalleryImage", b =>
                {
                    b.HasOne("LevelsOnIceSalon.Domain.Entities.Service", "Service")
                        .WithMany("GalleryImages")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Service");
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.Service", b =>
                {
                    b.HasOne("LevelsOnIceSalon.Domain.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.Service", b =>
                {
                    b.Navigation("AppointmentRequests");

                    b.Navigation("GalleryImages");
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("LevelsOnIceSalon.Domain.Entities.TeamMember", b =>
                {
                    b.Navigation("AppointmentRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
